stages:
  train:
    matrix:
      distribution: ${distributions}
      dataset: ${datasets}
    cmd: python scripts/multivariate_unconditional.py --log-level ${log-level} --log-file results/${item.distribution}_${item.dataset}/train.log --experiment-name unconditional-${item.dataset} train ${item.distribution} ${item.dataset} results/${item.distribution}_${item.dataset}
    params:
    - log-level
    - common.seed
    - common.data_kwds.n_samples
    - common.data_kwds.noise
    - common.data_kwds.scale
    - distributions.${item.distribution}*
    deps:
    - scripts/multivariate_unconditional.py
    - pyproject.toml
    - src/mctm
    metrics:
    - results/${item.distribution}_${item.dataset}/metrics.yaml
    outs:
    - results/${item.distribution}_${item.dataset}/mcp
    - results/${item.distribution}_${item.dataset}/train.log
