stages:
  unconditional:
    matrix:
      distribution: ${unconditional_distributions}
      dataset: ${datasets}
    cmd: python scripts/train.py --log-level ${log-level} --log-file results/unconditional_${item.distribution}_${item.dataset}/train.log --experiment-name unconditional-${item.dataset} unconditional ${item.distribution} ${item.dataset} results/unconditional_${item.distribution}_${item.dataset}
    params:
    - log-level
    - seed
    - datasets.${item.dataset}*
    - unconditional_distributions.${item.distribution}*
    deps:
    - scripts/train.py
    - pyproject.toml
    - src/mctm
    metrics:
    - results/unconditional_${item.distribution}_${item.dataset}/metrics.yaml
    outs:
    - results/unconditional_${item.distribution}_${item.dataset}/mcp
    - results/unconditional_${item.distribution}_${item.dataset}/train.log

  conditional:
    matrix:
      distribution: ${conditional_distributions}
      dataset: ${datasets}
    cmd: python scripts/train.py --log-level ${log-level} --log-file results/conditional_${item.distribution}_${item.dataset}/train.log --experiment-name conditional-${item.dataset} conditional ${item.distribution} ${item.dataset} results/conditional_${item.distribution}_${item.dataset}
    params:
    - log-level
    - seed
    - datasets.${item.dataset}*
    - conditional_distributions.${item.distribution}*
    deps:
    - scripts/train.py
    - pyproject.toml
    - src/mctm
    metrics:
    - results/conditional_${item.distribution}_${item.dataset}/metrics.yaml
    outs:
    - results/conditional_${item.distribution}_${item.dataset}/mcp
    - results/conditional_${item.distribution}_${item.dataset}/train.log

  unconditional_hybrid:
    matrix:
      distribution: ${unconditional_hybrid_distributions}
      dataset: ${datasets}
    cmd: python scripts/train_hybrid.py --log-level ${log-level} --log-file results/unconditional_hybrid_${item.distribution}_${item.dataset}/train.log --experiment-name unconditional-hybrid-${item.dataset} unconditional_hybrid ${item.distribution} ${item.dataset} results/unconditional_hybrid_${item.distribution}_${item.dataset}/
    params:
    - log-level
    - seed
    - datasets.${item.dataset}*
    - unconditional_hybrid_distributions.${item.distribution}*
    deps:
    - scripts/train_hybrid.py
    - pyproject.toml
    - src/mctm
    metrics:
    - results/unconditional_hybrid_${item.distribution}_${item.dataset}/metrics.yaml
    outs:
    - results/unconditional_hybrid_${item.distribution}_${item.dataset}/train.log
    - results/unconditional_hybrid_${item.distribution}_${item.dataset}/mcp
