stages:
  train:
    foreach: ${distributions}
    do:
      cmd: python scripts/multivariate_unconditional.py --log-level ${log-level} --log-file train_${key}.log --experiment-name unconditional-${common.dataset} train@${key} results/${key}
      params:
      - common.seed
      - common.dataset
      - common.data_kwds
      - distributions.${key}
      - distributions.${key}.distribution_kwds
      - distributions.${key}.fit_kwds
      deps:
      - scripts/multivariate_unconditional.py
