stages:
  train-sim:
    matrix:
      dataset: ${sim_datasets}
      model: ${sim_models}
    cmd: python scripts/train.py --log-level ${log-level} --log-file train.log --experiment-name ${item.model}-${item.dataset.type}-${item.dataset.name} train-sim@${key} ${item.dataset.type} ${item.dataset.name} results/${item.model}_${item.dataset.type}_${item.dataset.name} --test-mode=${testmode}
    params:
    - seed
    - textwidth
    - params/${item.dataset.type}/dataset.yaml:
      - dataset_kwargs.${item.dataset.name}*
    - params/${item.dataset.type}/${item.dataset.name}/${item.model}.yaml:
    deps:
    - scripts/train.py
    - pyproject.toml
    - src/mctm
    metrics:
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/metrics.yaml
    outs:
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/mcp
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/train.log
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/dataset.pdf
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/samples.pdf

  train-benchmark:
    matrix:
      dataset: ${benchmark_datasets}
      model: ${benchmark_models}
    cmd: echo python scripts/train.py --log-level ${log-level} --log-file train.log --experiment-name ${item.model}-${item.dataset.type}-${item.dataset.name} train@${key} results/${item.model}_${item.dataset.type}_${item.dataset.name} --test-mode=${testmode}
    params:
    - log-level
    - seed
    - textwidth
    - params/${item.dataset.type}/dataset.yaml:
      - ${item.dataset.name}*
    - params/${item.dataset.type}/${item.model}.yaml:
    deps:
    - scripts/train.py
    - pyproject.toml
    - src/mctm
    - data/${item.dataset.type}/${item.dataset.name}_train.npy
    - data/${item.dataset.type}/${item.dataset.name}_validate.npy
    metrics:
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/metrics.yaml
    outs:
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/mcp
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/train.log
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/dataset.pdf
    - results/${item.model}_${item.dataset.type}_${item.dataset.name}/samples.pdf
