stages:
  unconditional:
    matrix:
      distribution: ${unconditional_distributions}
      dataset: ${datasets}
    cmd: python scripts/train.py --log-level ${log-level} --log-file results/unconditional_${item.distribution}_${item.dataset}/train.log --experiment-name unconditional-${item.dataset} unconditional ${item.distribution} ${item.dataset} results/unconditional_${item.distribution}_${item.dataset}
    params:
    - log-level
    - common.seed
    - common.data_kwds.n_samples
    - common.data_kwds.noise
    - common.data_kwds.scale
    - unconditional_distributions.${item.distribution}*
    deps:
    - scripts/train.py
    - pyproject.toml
    - src/mctm
    metrics:
    - results/unconditional_${item.distribution}_${item.dataset}/metrics.yaml
    outs:
    - results/unconditional_${item.distribution}_${item.dataset}/mcp
    - results/unconditional_${item.distribution}_${item.dataset}/train.log

  conditional:
    matrix:
      distribution: ${conditional_distributions}
      dataset: ${datasets}
    cmd: python scripts/train.py --log-level ${log-level} --log-file results/conditional_${item.distribution}_${item.dataset}/train.log --experiment-name conditional-${item.dataset} conditional ${item.distribution} ${item.dataset} results/conditional_${item.distribution}_${item.dataset}
    params:
    - log-level
    - common.seed
    - common.data_kwds.n_samples
    - common.data_kwds.noise
    - common.data_kwds.scale
    - conditional_distributions.${item.distribution}*
    deps:
    - scripts/train.py
    - pyproject.toml
    - src/mctm
    metrics:
    - results/conditional_${item.distribution}_${item.dataset}/metrics.yaml
    outs:
    - results/conditional_${item.distribution}_${item.dataset}/mcp
    - results/conditional_${item.distribution}_${item.dataset}/train.log
