name: py3_8
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.8.5
  - pytorch
  - numpy==1.24.*
  - pandas==1.5.*
  - seaborn==0.12.*
  - scikit-learn==1.2.*
  - tensorflow==2.9.*
  - mlflow==2.5.0
  - pip
  - pip:
    - tensorflow_datasets==4.9.2
    - git+https://github.com/MArpogaus/TensorFlow-Probability-Bernstein-Polynomial-Bijector.git@2ceb26e
    - git+https://github.com/facebookincubator/flowtorch.git
    - -e .