log-level: info
common:
  seed: 1
  dataset: moons
  data_kwds:
    n_samples: 2000
    noise: 0.05
    scale: true

distributions:
  bernstein_flow:
    distribution_kwds: &distribution_kwds
      order: 25
      low: -3
      high: 3
      smooth_bounds: true
      allow_flexible_bounds: true
    fit_kwds:
      epochs: 1000
      validation_split: 0.1
      batch_size: 32
      learning_rate: 0.001
      lr_patience: 10
  multivariate_bernstein_flow:
    distribution_kwds: *distribution_kwds
    fit_kwds:
      epochs: 1000
      validation_split: 0.1
      batch_size: 32
      learning_rate: 0.001
      lr_patience: 10
  multivariate_normal:
    distribution_kwds: {}
    fit_kwds:
      epochs: 1000
      validation_split: 0.1
      batch_size: 32
      learning_rate: 0.001
      lr_patience: 10
  masked_autoregressive_bernstein_flow:
    distribution_kwds: *distribution_kwds
    parameter_kwds:
      hidden_units: [16, 16]
      activation: relu
    fit_kwds:
      epochs: 1000
      validation_split: 0.1
      batch_size: 32
      learning_rate: 0.001
      lr_patience: 10
  coupling_bernstein_flow:
    distribution_kwds:
      <<: *distribution_kwds
      coupling_layers: 2
    parameter_kwds:
      hidden_units: [16, 16]
      activation: relu
      batch_norm: false,
    fit_kwds:
      epochs: 1000
      validation_split: 0.1
      batch_size: 32
      learning_rate: 0.001
      lr_patience: 10
