log-level: info
seed: 1
textwidth: 487.8225
testmode: false

sim_datasets:
- type: sim
  name: moons
- type: sim
  name: circles

benchmark_datasets:
- type: benchmark
  name: bsds300
- type: benchmark
  name: gas
- type: benchmark
  name: hepmass
- type: benchmark
  name: miniboone
- type: benchmark
  name: power

sim_models:
- conditional_coupling_flow
- conditional_elementwise_flow
- conditional_masked_autoregressive_flow
- conditional_multivariate_flow
- conditional_multivariate_normal
- unconditional_coupling_flow
- unconditional_elementwise_flow
- unconditional_hybrid_coupling_flow
- unconditional_hybrid_masked_autoregressive_flow_first_dim_masked
- unconditional_masked_autoregressive_flow
- unconditional_multivariate_flow
- unconditional_multivariate_normal

benchmark_models:
# - unconditional_coupling_flow
# - unconditional_hybrid_coupling_flow
# - unconditional_multivariate_flow
# - unconditional_multivariate_normal
- unconditional_elementwise_flow
- unconditional_hybrid_masked_autoregressive_flow_first_dim_masked
- unconditional_masked_autoregressive_flow

malnutrition_kwargs:
  data_path: datasets/malnutrition/india.raw
  targets: [stunting, wasting, underweight]
  covariates: [mage]
