compile_kwargs:
  jit_compile: false
fit_kwargs:
  batch_size: 256
  early_stopping: false
  epochs: 200
  learning_rate:
    scheduler_kwargs:
      decay_steps: 200
      initial_learning_rate: 0.01
    scheduler_name: cosine_decay
  monitor: val_loss
  reduce_lr_on_plateau: false
  validation_split: 0.1
  verbose: true
model_kwargs:
  distribution: multivariate_flow
  distribution_kwargs:
    allow_flexible_bounds: false
    bijector_name: bernstein_poly
    bounds: smooth
    high: 4
    low: -4
    order: 100
    scale: false
    shift: false
  parameter_kwargs:
    activation: relu
    batch_norm: true
    conditional: true
    conditional_event_shape: 1
    dropout: 0
    hidden_units:
    - 16
    - 16
