compile_kwargs:
  jit_compile: true
fit_kwargs:
  batch_size: 256
  early_stopping: false
  reduce_lr_on_plateau: false
  epochs: 10
  learning_rate:
    scheduler_kwargs:
      initial_learning_rate: 0.01
      decay_steps: 100
      # alpha: 0.01
    scheduler_name: cosine_decay
  monitor: val_loss
  validation_split: 0.1
  verbose: true
model_kwargs:
  distribution: masked_autoregressive_flow
  distribution_kwargs:
    allow_flexible_bounds: false
    bijector_name: bernstein_poly
    bounds: smooth
    high: 4
    low: -4
    # scale_to_domain: true
    num_layers: 1
    order: 100
    scale: false
    shift: false
    base_distribution_kwargs:
      distribution_type: truncated_normal
  parameter_kwargs:
    activation: tanh
    hidden_units:
    - 16
    - 32
    - 64
