compile_kwargs:
  jit_compile: true
fit_kwargs:
  batch_size: 256
  early_stopping: false
  epochs: 200
  learning_rate:
    scheduler_kwargs:
      decay_steps: 200
      initial_learning_rate: 0.01
    scheduler_name: cosine_decay
  monitor: val_loss
  reduce_lr_on_plateau: false
  validation_split: 0.1
  verbose: true
model_kwargs:
  base_checkpoint_path: false
  base_distribution: elementwise_flow
  base_distribution_kwargs:
    allow_flexible_bounds: true
    # base_distribution_kwargs:
    #   distribution_type: truncated_normal
    bijector_name: bernstein_poly
    bounds: smooth
    high: 4
    low: -4
    order: 100
    scale: false
    shift: false
  base_parameter_kwargs:
    conditional: false
    dtype: float32
  distribution: coupling_flow
  distribution_kwargs:
    allow_flexible_bounds: false
    bijector_name: bernstein_poly
    bounds: identity
    high: 1
    low: 0
    # scale_to_domain: True
    num_layers: 4
    order: 64
    scale: false
    shift: false
  freeze_base_model: false
  parameter_kwargs:
    activation: relu
    batch_norm: false
    dropout: 0
    hidden_units:
    - 16
    - 32
