compile_kwargs:
  jit_compile: true
fit_kwargs:
  batch_size: 256
  early_stopping: 50
  epochs: 110
  learning_rate:
    batch_size: 256
    early_stopping: false
    epochs: 10
    learning_rate:
      scheduler_kwargs:
        decay_steps: 100
        initial_learning_rate: 0.01
      scheduler_name: cosine_decay
    monitor: val_loss
    reduce_lr_on_plateau: false
    validation_split: 0.1
    verbose: true
  lr_patience: 1
  monitor: val_loss
  reduce_lr_on_plateau: false
  validation_split: 0.1
  verbose: true
model_kwargs:
  distribution: coupling_flow
  distribution_kwargs:
    allow_flexible_bounds: true
    bijector_name: bernstein_poly
    bounds: smooth
    high: 3
    low: -3
    num_layers: 1
    order: 50
    scale: false
    shift: false
  parameter_kwargs:
    activation: tanh
    batch_norm: false
    dropout: 0
    hidden_units:
    - 16
    - 16
    - 16
