compile_kwargs:
  jit_compile: true
fit_kwargs:
  batch_size: 256
  early_stopping: 4
  epochs: 10000
  learning_rate:
    batch_size: 256
    early_stopping: false
    epochs: 10
    learning_rate:
      scheduler_kwargs:
        decay_steps: 100
        initial_learning_rate: 0.01
      scheduler_name: cosine_decay
    monitor: val_loss
    reduce_lr_on_plateau: false
    validation_split: 0.1
    verbose: true
  lr_patience: 25
  lr_reduction_factor: 0.5
  monitor: val_loss
  reduce_lr_on_plateau: true
  validation_split: 0.1
  verbose: true
model_kwargs:
  base_checkpoint_path: false
  base_distribution: elementwise_flow
  base_distribution_kwargs:
    allow_flexible_bounds: true
    bijector_name: bernstein_poly
    bounds: smooth
    high: 3
    low: -3
    order: 25
    scale: false
    shift: false
  base_parameter_kwargs:
    conditional: false
    dtype: float32
  distribution: coupling_flow
  distribution_kwargs:
    allow_flexible_bounds: true
    bijector_name: bernstein_poly
    bounds: smooth
    high: 1
    low: 0
    num_layers: 1
    order: 25
    scale: false
    shift: false
  freeze_base_model: false
  parameter_kwargs:
    activation: relu
    batch_norm: false
    dropout: 0
    hidden_units:
    - 1024
    - 1024
    - 1024
