compile_kwargs:
  jit_compile: true
fit_kwargs:
  batch_size: 256
  early_stopping: false
  epochs: 200
  learning_rate:
    scheduler_kwargs:
      decay_steps: 200
      initial_learning_rate: 0.01
    scheduler_name: cosine_decay
  monitor: val_loss
  reduce_lr_on_plateau: false
  validation_split: 0.1
  verbose: true
model_kwargs:
  distribution: elementwise_flow
  distribution_kwargs:
    allow_flexible_bounds: false
    base_distribution_kwargs:
      distribution_type: truncated_normal
    bijector_name: bernstein_poly
    bounds: smooth
    high: 4
    low: -4
    order: 100
    scale: false
    shift: false
  parameter_kwargs:
    conditional: false
    dtype: float32
